#!/usr/bin/env bash

echo "Stopping all active Quadlet containers (systemd --user units)..."

# Get all running services
services=$(systemctl --user list-units --type=service --state=running --no-legend | awk '{print $1}')

for service in $services; do
  # Get the unit file path (if generated by Quadlet, it will be under /run/user/.../generator/)
  unit_path=$(systemctl --user show "$service" -p FragmentPath | cut -d= -f2)

  if [[ "$unit_path" == /run/user/*/systemd/generator/* ]]; then
    # Further verify it's from a .container file (optional: check for actual container existence)
    echo "Stopping Quadlet container: $service"
    systemctl --user stop "$service"
  fi
done

echo "Done."

